### ISSUE TITLE
Error and crashing

### ISSUE THREAD

**Issue by hound12321** [RussDev7/External-Fishing-Bot-For-Minecraft#2]
![No Volume Detection](https://github.com/RussDev7/External-Fishing-Bot-For-Minecraft/assets/19316565/65be2261-8eb7-46a3-8e7d-5768533a0c60)
![Error msg](https://github.com/RussDev7/External-Fishing-Bot-For-Minecraft/assets/19316565/a127f127-6aa3-43d3-a019-f502197bdf65)

And when i click on capture to start capturing the sound it give me this error message

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentException: Process with an Id of 10432 is not running.
   at System.Diagnostics.Process.GetProcessById(Int32 processId, String machineName)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at WindowsFormsApp2.Form1.timer10_Tick(Object sender, EventArgs e)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Minecraft Auto-Fishing Bot v2.41
    Assembly Version: 1.0.0.0
    Win32 Version: 2.4.1.0
    CodeBase: file:///C:/Users/aaron/Desktop/Minecraft.Auto-Fishing.Bot.v2.41/Minecraft%20Auto-Fishing%20Bot%20v2.41.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9220.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9220.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

Am i doing somthing wrong? i download the file extrat it then run as admin but it is still giving me issues

**Comment by RussDev7** [comment]
Looking at this, this error should never had happened. Did you close your game after you opened up the tool? For now I will close this post until you get a chance to respond.

**Comment by hound12321** [comment]
nope i start the program while the game is open and the location where i want to start fishing and it gives this error almost seems like its trying to do something with the audio and then can't so crashes, though it only lets me use "Javaw" not just "Java" in the JavaName setting at the bottom it can't seem to detect it unless with newer versions I'm supposed to use the "Javaw" setting I'm trying to use it with the latest version of minecraft

**Comment by hound12321** [comment]
headed off to work ill be back in about 3ish hours for the time of this post if you read this while im gone

**Comment by hound12321** [comment]
im back for now
