### ISSUE TITLE
Java/Bedrock

### ISSUE THREAD

**Issue by Orlovgg** [RussDev7/External-Fishing-Bot-For-Minecraft#3]
Good afternoon Is this only for Java?

**Comment by RussDev7** [comment]
Hello! Within the releases [v2.40](https://github.com/RussDev7/External-Fishing-Bot-For-Minecraft/releases/tag/2.40), there is a bedrock version you can download pre-compiled. If you would like to compile it yourself, a bedrock version can be found [here](https://github.com/RussDev7/External-Fishing-Bot-For-Minecraft/tree/main/Minecraft-Fishing-Bot%20v2.40%20-%20Bedrock).
